### ISSUE TITLE
User:Pass Format

### ISSUE THREAD

**Issue by sporezzz** [Plasmonix/Netflixer#30]
is there a certain format i should be using because this does not work for me

**Comment by YashvirGaming** [comment]
> is there a certain format i should be using because this does not work for me

I fix the checker myself, also this his checker ain't no api lol its basic Netflix direct login
It will never work as Nowadays Netflix.com has Recaptcha on their site, and this python source doesn't have that :D

BTW i fixed the checker by removing some old codes of his adding **NEW NON SKIP Hits Api**
It doesnt skip any hits

Also 
I added more Captures,  
see picture below
![image](https://github.com/Plasmonix/Netflixer/assets/64865096/eadd1e7e-e494-4356-9bd8-737c6a998909)

**Comment by YashvirGaming** [comment]
@Plasmonix  how to fix the useragent error 
also give me python code to use proxy as Residential proxyy
**IP:PORT:USername:Pass** 
How to implement this type for proxy into the python ?
